### ISSUE TITLE
npm installs old version

### ISSUE THREAD

**Issue by JohnPaulHarold** [spacebetween/imageMapTiles#1]
installing this via npm installs a version before this commit https://github.com/spacebetween/imageMapTiles/commit/6451b5ff59a776980a0895afbd2507590cb5d9bd

I'm not massively familar with publishing node modules myself, but I'm guessing npm is pulling down your 0.0.1 release, https://github.com/spacebetween/imageMapTiles/commit/ec5801b000ba8fe9ec142c4f5f9167b9490dccc5

I worked around this by installing with the latest commit hash, but just raising it here in case you want to update the npm repos.

**Comment by GeneralTyres** [comment]
What is the command for installing a specific commit?

**Comment by JohnPaulHarold** [comment]
You can install directly from github doing this:

`npm i git+${ssh|https}://git@github.com:${github user}/${github repo}.git#${commit hash}`

so, to get the latest from this repo:

`npm i git+ssh://git@github.com:spacebetween/imageMapTiles.git#bd6759d`

You might need to escape the hash `\#` before the commit on Windows, not 100% sure on that. I only tested this on OSX, but I'd hope Windows builds OK as well.

@MCooke could you perhaps make a new release, pointing at the most recent commit?

**Comment by MCooke** [comment]
Thanks @JohnPaulHarold .

I'll push out a new release today.

**Comment by GeneralTyres** [comment]
Thank you for replying @JohnPaulHarold . Love your project by the way @MCooke . Took me days to find this repository and it was exactly what I was looking for.

**Comment by MCooke** [comment]
Appreciated @GeneralTyres, I had a similar problem :)

I've updated NPM to point to the most recent release, thanks for the prodding all.
